server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/pms
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  devtools:
    livereload:
      enabled: true
      # thymeleaf cache 비활성화
  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


